### ISSUE TITLE
Link to docs is 404 error

### ISSUE THREAD

**Issue by tseemann** [mad-lab/transit#10]
http://saclab.tamu.edu/essentiality/transit/transit.html

Seems to be broken

The whole lab site is down?

**This site can’t be reached
saclab.tamu.edu refused to connect.**

**Comment by mad-lab** [comment]
Unfortunately our server is undergoing some maintenance right now, and that link will be down for the next day or so.

I can let you know here as soon as it comes back.

P.S. The documentation itself can be found here:

http://transit.readthedocs.io/en/latest/

**Comment by tseemann** [comment]
Thanks! 

Maybe update your README link as `readthedocs.io` will be more permanent?
