### ISSUE TITLE
wx.open error on mac python2.7 

### ISSUE THREAD

**Issue by shangyan0517** [mad-lab/transit#13]
get error when trying python2.7 tpp.py

`
❯ python2.7 tpp.py
Traceback (most recent call last):
  File "tpp.py", line 26, in <module>
    pytpp.__main__.run_main()
  File "~/transit/src/pytpp/__main__.py", line 39, in run_main
    main(*args, **kwargs)
  File "~/transit/src/pytpp/__main__.py", line 47, in main
    form = MyForm(vars)
  File "~/transit/src/pytpp/tpp_gui.py", line 66, in __init__
    self.InitFiles(panel,sizer)
  File "~/transit/src/pytpp/tpp_gui.py", line 102, in InitFiles
    self.picker3 = wx.lib.filebrowsebutton.FileBrowseButton(panel, id=wx.ID_ANY, dialogTitle='Please select the reference genome', fileMode=wx.OPEN, fileMask='*.fna;*.fasta;*.fa', size=(400,30), startDirectory=os.path.dirname(vars.ref), initialValue=vars.ref, labelText='')
AttributeError: 'module' object has no attribute 'OPEN'
`

Reason:
The correct constant to use is wx.FD_OPEN instead of wx.OPEN, the later may have worked in older wxPython versions. But even documentation for version 2.8.9.2 says wx.FD_OPEN.

Solution
Substitue `wx.OPEN` in PATH/src/pytpp/tpp_gui.py to `wx.FD_OPEN`
Substitue `wx.CHANGE_DIR` to `wx.FD_CHANGE_DIR`

**Comment by subsid** [comment]
Thanks @shangyan0517 . This issue has been fixed in version `2.3.0`
