### ISSUE TITLE
Problem with Benjamini-Hochberg Correction on TRANSIT 2.3.3 GUI on Windows?

### ISSUE THREAD

**Issue by 4rn01d** [mad-lab/transit#17]
Hello,

I am have updated my TRANSIT to 2.3.3 on my Windows laptop; however, now, I am having difficulty with performing the Resampling pipeline on this new version via the GUI interface (I used to be able to perform it on 2.3.2).  When attempting to run a Resampling pipeline, it would work properly until it reaches the Bejamini-Hochberg Correction stage, where it would output an Attribute error (see screenshot below – This is a screenshot of my command prompt outputting step-by-step progress as the TRANSIT 2.3.3 GUI runs the Resampling pipeline.  This error is also outputted if I run it on my Python 2.7 window):

![2018-12-26](https://user-images.githubusercontent.com/45212261/51081142-e72f3380-16b6-11e9-94df-59a119687ef3.png)

This attribute error seems to referring to an attribute ‘Z’, which I believe refers to a Z-score, but I find this odd because I do not remember previous versions of TRANSIT’s Resampling pipeline calculating/outputting Z-scores (I do not see any Z-scores outputted in data files from my previous Resampling runs on TRANSIT 2.3.2).  I have attempted to look into the program’s Python scripts, uninstalled and reinstalled Python AND TRANSIT 2.3.3, but I still continue to receive this error in the GUI interface.

Has anyone received such an error too and/or know how to resolve this?  Please let me know if any more information is needed.

As a further note, I have ran the wig files portrayed in the screenshot on TRANSIT 2.3.2 and would receive no error and would successfully get an outputted file.

Thank you for your time!
- Arnold

**Comment by subsid** [comment]
Hey Arnold,

Thanks for the report. There was a minor bug in resampling, while initializing GUI inputs  in `2.3.3`. This has been fixed in version `2.3.4`.
