### ISSUE TITLE
Upgraded Transit, program doesn't open 

### ISSUE THREAD

**Issue by ChidiAkusobi** [mad-lab/transit#19]
Hello, 

I tried running the 'Track View' feature on the older version of the Transit program and was getting this error: 
"TypeError: in method 'Window_SetSizeHints', expected argument 2 of type 'int" 

Not exactly sure how to fix it, I decided to upgrade transit by installing the package. Now when I try and open the program by simply typing transit, I get the message below:. Any ideas on how to trouble shoot? 

Best, 
Chidi 

~New Error Message~

Chidis-MacBook-Pro:~ chidiakusobi$ transit 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/transit", line 6, in <module>
    from pytransit.__main__ import run_main
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytransit/__main__.py", line 16, in <module>
    from pubsub import pub
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pubsub/pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax
Chidis-MacBook-Pro:~ chidiakusobi$

**Comment by subsid** [comment]
Hi Chidi,

We recently made transit not depend on the pypubsub module (for commandline mode). If you'd like to use Transit from the Graphical interface, you have to install the latest version of wxPython (4+) and pypubsub (3.3) seperately. (https://transit.readthedocs.io/en/latest/transit_install.html#requirements)

Executing this command should install all the dependencies:

`pip install numpy scipy pillow "pypubsub<4.0" "matplotlib<3.0" statsmodels wxPython`

Note: If you have an older version of wxPython (< 4), you may have to uninstall that and reinstall the 4+ version.
