### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [mad-lab/transit#20]
Hello,
the Debian Med team is maintaining transit for official Debian.  The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL.  If you are interested that we continue to maintain transit in official Debian (and that users of other modern distributions will have no problems to install transit on their systems) I'd recommend you port your code to Python3.  The 2to3 tool might be of great help here.
Kind regards, Andreas.

**Comment by ioerger** [comment]
Transit has already been ported to Python3 internally, and will be
available in Transit release 3.0, which is imminent.

Tom

**Comment by tillea** [comment]
On Tue, Jul 09, 2019 at 06:43:05AM -0700, ioerger wrote:
> Transit has already been ported to Python3 internally, and will be
> available in Transit release 3.0, which is imminent.
Very cool!  Thanks a lot for the quick and promising reply, Andreas.

**Comment by subsid** [comment]
Release v3.0 now supports Python 3.
