### ISSUE TITLE
tnseq_stats for combined wig file are incorrect

### ISSUE THREAD

**Issue by jenjane118** [mad-lab/transit#24]
Using command line to generate tn stats from a combined .wig file, the stats gives the stats for the first column in the file (the first sample entered on in the export to combined wig command), rather than any combined stats. Is this the intention of this tool? I understood it would give combined insertion density, etc for all replicates/samples included in the combined wig file.

transit export combined_wig B_R1.wig,D_R1.wig,G_R1.wig $my_path/refseqs/mbovis/mbovis.prot_table bovis_combined_nonorm.wig -n nonorm
transit tnseq_stats bovis_combined_nonorm.wig -o bovis_combined_nonorm_stats.dat

**Comment by ioerger** [comment]
You have to preface a combined_wig file with '-c' for this command.

Tom
