### ISSUE TITLE
HMM analysis doesn't work with latest numpy

### ISSUE THREAD

**Issue by afkoeppel** [mad-lab/transit#4]
Hello,

I'm running TRANSIT v2.0.2 on macOS Sierra v.10.12.4.  I have Python 2.7.13,  numpy 1.12.0, scipy 0.19.0, matplotlib 1.4.3, pillow 4.0.0, and the repackaged version of wxpython linked in the TRANSIT documentation.  
I was able to successfully load in my annotation and wig files, generate the track view scatter plots, and QC plots, and do the binomial and griffin analyses.  
However, when I try to do the HMM analysis it got started, and ran for awhile, but then I got the following output:

[hmm] Starting HMM Method
[hmm] Getting Data
[hmm] Combining Replicates as 'Sum'
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytransit/analysis/hmm.py:495: RuntimeWarning: divide by zero encountered in log
  delta[:,t] = nus.max(1) + numpy.log(b_o)
[TRANSIT] Error: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytransit/transit_gui.py", line 1886, in RunMethod
    thread = threading.Thread(target=M.Run())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytransit/analysis/hmm.py", line 323, in Run
    (Q_opt, delta, Q) = self.viterbi(A, B, PI, O)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytransit/analysis/hmm.py", line 503, in viterbi
    Q_opt.insert(0, Q[Q_opt[0],t+1])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I tried the analysis on the example data and got the same result.  It looked from the error text like something in numpy might be involved, so I tried downgrading to numpy 1.6.1, and scipy 0.14.0 (0.19.0 was not compatible with the older numpy).   This appears to have solved the problem (at least for me) but I wanted you to be aware that it doesn't work with the latest scipy and numpy, so that you can update the documentation (http://pythonhosted.org/tnseq-transit/transit_install.html install page indicates that versions above those stated should work).

**Comment by mad-lab** [comment]
Thanks! You're right numpy changed some of it's behavior, which causes problems. I just committed a fix to the master branch. For now, if you're using git, you can pull/download the new changes and it should work with the latest numpy.

We should be releasing a new version (and packaging it for pip) in the near future.

**Comment by mad-lab** [comment]
Uploaded an additional fix to make TRANSIT compatible with boolean array comparisons (e.g. X.any() ). This should make the HMM compatible with the latest versions of numpy. 

Closing this issue for now.
